name: Ruby

on:
  push:
    branches:
      - master

  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby:
          - '3.3.6'

    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Prepare js
      run: |
        cd js/instrumenter
        yarn install --frozen-lockfile
        yarn run build
    - name: Tests
      run: bundle exec rspec
    - name: Build release
      run: ./scripts/release.sh
